--- 
data0: 
  - 
    FROM: srudeep.9@gmail.com
  - 
    TONAME: srudeep
  - 
    SUBJECT: "TEST mail"
  - 
    MESSAGE: "Hi {},\n\


              This is a test email. \n\


              Regards,\n\
              Srudeep "

data1:
  - 
    FROM: srudeep.9@gmail.com
  - 
    TONAME: srudeep
  - 
    SUBJECT: "This is Testnew1"
  - 
    MESSAGE: "Hi {},\n\


              This is a test1 email. Your application is running succesfully.\n\


              Regards,\n\
              Srudeep "
